#!/usr/bin/env bash
# Copy configs from this repo to the live system.
# Run from anywhere; the inverse of copy-configs.sh.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

copy_file() {
  local src="$REPO_DIR/$1"
  local dst="$2"
  if [ ! -f "$src" ]; then
    echo "skip (not found): $src" >&2
    return
  fi
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "copied $1 -> $dst"
}

copy_dir() {
  local name="$1"
  local src="$REPO_DIR/$name"
  local dst="$CONFIG/$name"
  if [ ! -d "$src" ]; then
    echo "skip (not found): $src" >&2
    return
  fi
  mkdir -p "$dst"
  rsync -a --exclude='*.bak' "$src/" "$dst/"
  echo "copied $name/ -> $dst/"
}

# Names of currently connected monitors, one per line, via `hyprctl monitors`.
detect_monitors() {
  if command -v hyprctl >/dev/null 2>&1 && hyprctl monitors >/dev/null 2>&1; then
    hyprctl monitors | awk '/^Monitor /{print $2}'
  fi
}

# Prompt for a monitor name, offering the detected list (by number) as a shortcut.
# Reads the detected_monitors array set up by the caller.
pick_monitor() {
  local prompt="$1"
  local choice
  if [ "${#detected_monitors[@]}" -gt 0 ]; then
    read -rp "$prompt (number or name): " choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#detected_monitors[@]}" ]; then
      printf '%s' "${detected_monitors[$((choice - 1))]}"
      return
    fi
  else
    read -rp "$prompt: " choice
  fi
  printf '%s' "$choice"
}

configure_monitors() {
  local machine_file="$CONFIG/hypr/machines/local.lua"

  if [ -f "$machine_file" ]; then
    rm -f "$machine_file"
    echo "removed existing $machine_file"
  fi

  if [ ! -t 0 ]; then
    echo "not running interactively, skipping monitor setup (create $machine_file by hand, see hyprland.lua)" >&2
    return
  fi

  local detected_monitors=()
  while IFS= read -r name; do
    [ -n "$name" ] && detected_monitors+=("$name")
  done < <(detect_monitors)

  echo "Monitor setup for this machine:"
  if [ "${#detected_monitors[@]}" -gt 0 ]; then
    local i
    for i in "${!detected_monitors[@]}"; do
      echo "  $((i + 1))) ${detected_monitors[$i]}"
    done
  else
    echo "  (could not auto-detect monitors — is Hyprland running? enter names manually)"
  fi

  local monitor_left monitor_right dual_answer flip_answer
  monitor_left="$(pick_monitor "Left monitor")"
  read -rp "Dual monitor setup? [y/N] " dual_answer

  local dual_monitor="false"
  local flip_left="false"
  monitor_right=""

  case "$dual_answer" in
    [Yy]*)
      dual_monitor="true"
      monitor_right="$(pick_monitor "Right monitor")"
      read -rp "Flip/rotate the left monitor 90°? [y/N] " flip_answer
      case "$flip_answer" in
        [Yy]*) flip_left="true" ;;
      esac
      ;;
  esac

  mkdir -p "$(dirname "$machine_file")"
  cat > "$machine_file" <<EOF
-- Generated by deploy-configs.sh. Delete this file to be prompted again.
return {
	monitorLeft = "$monitor_left",
	monitorRight = "$monitor_right",
	dualMonitor = $dual_monitor,
	flipLeftMonitor = $flip_left,
}
EOF
  echo "wrote $machine_file"
}

configure_monitors

copy_file ".zshrc" "$CONFIG/zsh/.zshrc"
copy_file "alacritty.toml" "$CONFIG/alacritty/alacritty.toml"
copy_dir hypr
copy_dir waybar

# hyprpaper only reads its config at its own startup, and hyprland.lua only
# (re)launches it on the compositor's "hyprland.start" event, so a config
# reload alone won't pick up wallpaper changes. Restart it here instead.
if command -v hyprctl >/dev/null 2>&1 && hyprctl monitors >/dev/null 2>&1; then
  pkill -x hyprpaper 2>/dev/null || true
  hyprctl dispatch 'hl.dsp.exec_cmd("hyprpaper")'
  echo "restarted hyprpaper"
fi

echo "done"
